[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_tests.py
addopts = --nomigrations --cov=apps.accounts --cov=apps.doctors --cov=apps.appointments --cov=apps.consultations --cov=apps.prescriptions --cov=apps.notifications --cov=apps.admin_api --cov-report=term-missing --cov-report=html
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
