# Generated by Django 5.2 on 2026-08-17 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="link_url",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this action (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acted_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arbitrary metadata e.g. {'appointment_id': 2, 'link': '/consult/2'}",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(
                default="bell",
                help_text="Lucide icon name (e.g. calendar-check, video, file-text)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="User who receives this notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                    ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                    ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                    ("CONSULT_STARTED", "Consultation Started"),
                    ("NEW_PRESCRIPTION", "New Prescription Ready"),
                    ("REVIEW_RECEIVED", "Review Received"),
                    ("PROFILE_INCOMPLETE", "Profile Incomplete"),
                    ("SYSTEM", "System Alert"),
                ],
                db_index=True,
                default="SYSTEM",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "created_at"],
                name="notif_recip_read_created_idx",
            ),
        ),
    ]
