# Generated by Django 5.2 on 2026-08-11 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED_BY_PATIENT", "Cancelled by Patient"),
                            ("CANCELLED_BY_DOCTOR", "Cancelled by Doctor"),
                            ("MISSED", "Missed"),
                        ],
                        db_index=True,
                        default="CONFIRMED",
                        max_length=30,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "fee_at_booking",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of consultation fee locked at booking time.",
                        max_digits=8,
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique booking reference code (e.g. ST-8XK2P3)",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Patient reported symptoms."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "start_time", "end_time"],
                        name="appointment_doctor__ffdb12_idx",
                    ),
                    models.Index(
                        fields=["patient", "start_time"],
                        name="appointment_patient_fbd73b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        help_text="1 for Monday through 7 for Sunday",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Start of doctor availability (e.g. 09:00)"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="End of doctor availability (e.g. 17:00)"
                    ),
                ),
                (
                    "slot_duration",
                    models.PositiveSmallIntegerField(
                        choices=[(15, "15 Minutes"), (30, "30 Minutes")],
                        default=30,
                        help_text="Duration per consultation slot in minutes.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Rule",
                "verbose_name_plural": "Availability Rules",
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "weekday"),
                        name="unique_doctor_weekday_availability",
                    )
                ],
            },
        ),
    ]
