# Generated by Django 5.2 on 2026-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityrule",
            name="slot_duration",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (15, "15 Minutes"),
                    (30, "30 Minutes"),
                    (45, "45 Minutes"),
                    (60, "60 Minutes"),
                ],
                default=30,
                help_text="Duration per consultation slot in minutes.",
            ),
        ),
    ]
