# Generated by Django 5.2 on 2026-08-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="notes",
        ),
        migrations.AddField(
            model_name="prescription",
            name="advice",
            field=models.TextField(
                blank=True, help_text="Special precautions, diet, or lifestyle advice."
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="follow_up_in_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Recommended follow-up in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="prescriptions/"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="verification_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique verification code for public authenticity validation",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(
                help_text="Clinical diagnosis or primary reason for prescription"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medicines",
            field=models.JSONField(
                default=list,
                help_text="List of dicts: [{'name': 'Paracetamol', 'dosage': '650mg', 'frequency': '1-0-1', 'duration': '5 days', 'instructions': 'After food'}]",
            ),
        ),
    ]
