# Generated by Django 5.2 on 2026-08-11 05:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon_name",
                    models.CharField(
                        default="stethoscope",
                        help_text="Lucide icon name (e.g., heart-pulse, sparkles, baby).",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        help_text="e.g. MBBS, MD (Cardiology), DM (AIIMS)",
                        max_length=150,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Total years of clinical practice."
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="State Medical Council or MCI registration number.",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Doctor introduction and experience summary.",
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("500.00"),
                        help_text="Consultation fee in INR.",
                        max_digits=8,
                    ),
                ),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                ("clinic_address", models.TextField(blank=True)),
                (
                    "avg_rating",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average rating score from 0.00 to 5.00.",
                        max_digits=3,
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total verified patient reviews."
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether doctor is currently accepting bookings.",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="doctors.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
                "ordering": ["-avg_rating", "-years_of_experience"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Star rating from 1 to 5.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "review_text",
                    models.TextField(blank=True, help_text="Detailed feedback."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="doctors.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Review",
                "verbose_name_plural": "Doctor Reviews",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "patient"),
                        name="unique_doctor_patient_review",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(fields=["city"], name="doctors_doc_city_584766_idx"),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["specialty"], name="doctors_doc_special_d47507_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["avg_rating"], name="doctors_doc_avg_rat_e17c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["consultation_fee"], name="doctors_doc_consult_68faeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["is_available"], name="doctors_doc_is_avai_dc2f4d_idx"
            ),
        ),
    ]
